name: Release

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: bindl-dev/bindl@main
      with:
        install-dir: bin

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - run: make deploy
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
